### ISSUE TITLE
Synonyme als separate Spalte?

### ISSUE THREAD

**Issue by KonradHoeffner** [DigitaleZukunft/glossar#15]
@FranziskaJahn:
>Die Primärbezeichnung "gleichwertig" mit den anderen Bezeichnungen in die erste Spalte zu schreiben, finde ich nicht so gut. Sie sollte deutlich als solche 
erkennbar sein, also z. B. fett hervorgehoben sein. Oder die Synonyme stehen erst in der 2. Zeile in Klammern. @Alex: Was denkst Du?
Bei den Beschreibungen könnte man auch gleich die Quelle noch mit in die Zelle reinnehmen (ans Ende in Klammern), dann hat man nicht noch eine Spalte mehr.

**Comment by KonradHoeffner** [comment]
Die Synonyme hatte ich am Anfang auch in einer zweiten Zeile, allerdings war das sehr platzverschwendend. Auf einem schmalen Fenster konnte man dann kaum noch etwas von der Beschreibung erkennen. Deinen ersten Vorschlag mit dem Hervorheben finde ich daher besser.

**Comment by astruebi** [comment]
Weniger Spalten finde ich besser. Kann man natürlich anders sehen. Probiere doch mal  die Primärbezeichnung in fett (aber die Spaltenköpfe sollten etwas größer als diese Schrift sein) und die anderen Bezeichner in derselben Spalte nach einem Zeilenumbruch in Klammern, nicht fett und kommasepariert.

**Comment by KonradHoeffner** [comment]
Fett habe ich ausprobiert, das sah mir aber zu übertrieben aus. Ich habe die Synonyme mal kursiv gesetzt, was mir persönlich am besten gefällt. Was sagt ihr dazu?

**Comment by astruebi** [comment]
Bitte brich vor den Synonymen immer um und setze sie in Klammern, ersetze alle Semikolons durch Kommas  und füge Leerzeichen nach allen Kommas ein, wo sie dahinter fehlen.

**Comment by KonradHoeffner** [comment]
Erledigt, ich schließe die Issue mal. Wenn es neue Anforderungen gibt, bitte wieder öffnen.
