### ISSUE TITLE
Link zu snik-graph

### ISSUE THREAD

**Issue by AlfredWinter** [DigitaleZukunft/glossar#21]
Jetzt wäre es cool, bei einem markierten Eintrag des Glossars in snik-graph springen zu können um dann dort den Zusammenhang mit anderen Begriffen explorieren zu können. Dazu müsste der graph geöffnet und auf den im Glossar ausgewählte Begriff zentriert werden und dieser markiert werden.

**Comment by KonradHoeffner** [comment]
Links zu SNIK Graph und LodView sind jetzt im Glossar vorhanden ganz rechts.

**Comment by KonradHoeffner** [comment]
P.S.: Es ist momentan ein Bug wegen einer anderen Funktionalität online, den schaffe ich aber heute nicht mehr und werde ihn Montag beheben, über das Wochenende ist es also gegebenenfalls nicht erreichbar.

**Comment by AlfredWinter** [comment]
Sagen Sie Bescheid, wenn es wieder geht.
